version: "3.6"
services:
  quorum-reporting:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quorum-reporting
    image: quorum-reporting
    ports:
      - "8998:3000"
      - "8997:4000"
    volumes:
      - ./config.docker.sample.toml:/config.toml